source("attic/cnf_verify3/occurrence_review/review_events.R")
install_observer()
check_case(list(c(1L, 2L), c(1L, 3L), c(-3L, 4L)), "simple retained HLA expansion")
check_case(list(c(1L, 1L, 2L), c(1L, 3L), c(-3L, 4L)), "duplicate target retained HLA expansion", TRUE)
stopifnot(review$counts$hla_containment_needs_virtual_target > 0L)
result = list(R = R.version.string, counts = review$counts, examples = review$examples)
saveRDS(result, file.path(review_dir, "hla_column_scope.rds"))
capture.output(print(result), file = file.path(review_dir, "hla_column_scope.txt"))
print(result$counts)
