"""Independent finite checks for the semantic review.

No production code or previous verification harness is imported. Boolean
enumeration proves the listed pointwise set implications; the explicit finite
models show why stronger or circular premises would be insufficient.

Run from the repository root:
  python3 attic/cnf_verify3/review_semantics/check_lemmas.py
"""

from itertools import product
import json
from pathlib import Path


counts = {}


def require(name, value):
    assert value, name
    counts[name] = counts.get(name, 0) + 1


def implies(left, right):
    return not left or right


# Freeze a comparison immediately before the registering index becomes a
# unit. E denotes precisely the older unit constraints, not the just-born
# candidate's constraint. Only the source can subsequently shrink.
for c, d, e, shrunk_c in product((False, True), repeat=4):
    contextual_before_birth = implies(c and e, d and e)
    source_shrinks = implies(shrunk_c, c)
    if contextual_before_birth and source_shrinks:
        require("freeze_prebirth_false_certificate", implies(shrunk_c and e, d))


# A dependency graph is permitted to omit earlier constraints. All edges must
# point backward in birth order. Exhaust every such graph with four births,
# and every pointwise membership pattern of the final clause and four units.
pairs = [(i, j) for i in range(4) for j in range(i)]
for edge_bits in product((False, True), repeat=len(pairs)):
    parents = {i: [] for i in range(4)}
    for edge, (i, j) in zip(edge_bits, pairs):
        if edge:
            parents[i].append(j)
    for c, *ranges in product((False, True), repeat=5):
        certificates = [
            implies(c and all(ranges[j] for j in parents[i]), ranges[i])
            for i in range(4)
        ]
        if all(certificates):
            require("acyclic_birth_discharge", implies(c, all(ranges)))


# A pending old restriction cannot widen a range that a recursive child has
# already restricted; two intersections commute even with delayed completion.
for c, parent, child in product((False, True), repeat=3):
    require("pending_parent_cannot_undo_child",
            (c and child and parent) == (c and parent and child))


# Unit merge writes the new representative before eliminating the candidate.
# Both intermediate conjunctions still denote the original two units.
for old, candidate in product((False, True), repeat=2):
    merged = old and candidate
    require("merge_before_candidate_elimination",
            (merged and candidate) == (old and candidate))
    require("merge_after_candidate_elimination",
            merged == (old and candidate))


# HLA using a retained donor. `other_d` and `other_c` aggregate non-pivot
# literals. This remains true if the donor was itself strengthened earlier
# while the target unit remained asserted.
for d, c, other_d, other_c in product((False, True), repeat=4):
    if implies(other_d, other_c):
        donor = d or other_d
        old_target = c or other_c
        virtual_target = c or not d or other_c
        require("hla_under_retained_donor",
                (donor and old_target) == (donor and virtual_target))


def models(clauses, universe):
    names = tuple(universe)
    answer = set()
    for values in product(*(universe[name] for name in names)):
        valuation = dict(zip(names, values))
        if all(any(valuation[s] in values for s, values in clause.items())
               for clause in clauses):
            answer.add(values)
    return answer


# Contextual containment against the target unit is automatic on its own
# symbol; using it as a raw unit-HLA premise can delete an essential unit.
universe = {"x": (0, 1, 2), "y": (0, 1)}
unit = {"x": {0, 1}}
donors = [{"x": {1, 2}, "y": {0}}, {"x": {1, 2}, "y": {1}}]
restricted = [{**donor, "x": donor["x"] & unit["x"]} for donor in donors]
original_models = models([unit] + donors, universe)
bad_removal_models = models(donors, universe)
require("circular_context_countermodel_is_real",
        original_models < bad_removal_models)
require("unit_restriction_keeps_current_formula",
        models([unit] + restricted, universe) == original_models)
require("removing_unit_after_sound_strengthening_is_valid",
        models(restricted, universe) == original_models)


# With two same-symbol constraints, reading the older representative's old
# incoming matrix as if it described its new merged range is invalid.
c = {0, 1}
first_birth = {0, 1}
second_birth = {1, 2}
merged = first_birth & second_birth
require("mutable_representative_countermodel_is_real",
        c <= first_birth and not c <= merged and not c <= second_birth)


# Cyclic certificates can all be true while physical containment is false.
# This graph cannot be generated by strictly older birth dependencies.
c, r0, r1 = {1}, {0}, {0}
require("cyclic_certificate_countermodel_is_real",
        c & r1 <= r0 and c & r0 <= r1 and not c <= r0 & r1)


# Lazy unit-HLA initialization: if a donor has no symbol changed since the
# beginning of this target's virtual proof, its comparison row is unchanged.
# An extension must touch every donor containing its changed symbol, including
# donors whose local row has not yet been allocated.
all_masks = (frozenset(), frozenset({0}), frozenset({1}), frozenset({0, 1}))
for original, extended, donor in product(all_masks, repeat=3):
    if not original <= extended:
        continue
    if not donor:
        require("unallocated_row_absent_changed_symbol",
                (donor <= original) == (donor <= extended))
    else:
        initial_bit = not donor <= original
        updated_bit = initial_bit and not donor <= extended
        require("allocated_row_monotone_update",
                updated_bit == (not donor <= extended))


result = {
    "checks": counts,
    "total": sum(counts.values()),
    "contextual_unit_hla_countermodel": {
        "original_models": sorted(original_models),
        "after_unsafe_unit_removal": sorted(bad_removal_models),
        "after_restriction_then_unit_removal": sorted(models(restricted, universe)),
    },
}
destination = Path(__file__).with_name("lemma_results.json")
destination.write_text(json.dumps(result, indent=2) + "\n")
for name, count in counts.items():
    print(f"{name}: {count}")
print(f"TOTAL: {result['total']}; all passed")
