# Base-R bridge and read-only instrumentation of the production HLA phase.
# Input consists only of R expressions generated by production_checks.py.
# Run from the repository root. No package installation or earlier harness is needed.

source("R/CnfFormula_simplify.R")
plain_simplify = simplify_cnf
review_stats = new.env(parent = emptyenv())

review_propagate = function(donors, target, universe) {
  possible = Map(setdiff, universe, lapply(names(universe), function(s) target[[s]]))
  if (any(!lengths(possible))) return(TRUE)
  repeat {
    changed = FALSE
    for (donor in donors) {
      live_symbols = names(donor)[vapply(names(donor), function(s) {
        length(intersect(donor[[s]], possible[[s]])) > 0L
      }, logical(1))]
      if (!length(live_symbols)) return(TRUE)
      if (length(live_symbols) == 1L) {
        s = live_symbols[[1L]]
        next_possible = intersect(possible[[s]], donor[[s]])
        if (length(next_possible) < length(possible[[s]])) {
          possible[[s]] = next_possible
          changed = TRUE
        }
      }
    }
    if (!changed) return(FALSE)
  }
}

review_boundary = function(frame) {
  entries = frame$entries
  live = which(!frame$eliminated & !frame$is_unit)
  units = which(!frame$eliminated & frame$is_unit)
  stopifnot(length(units) == length(frame$unit_domains))
  stopifnot(!anyDuplicated(unlist(lapply(entries[units], names))))
  for (s in names(frame$universe)) {
    registered = frame$symbol_registry[[s]]
    actual = live[vapply(entries[live], function(c) s %in% names(c), logical(1))]
    stopifnot(setequal(registered, actual))
    review_stats$registries = review_stats$registries + 1L
  }
  for (i in live) {
    for (unit in entries[units]) {
      s = names(unit)
      stopifnot(all(entries[[i]][[s]] %in% unit[[s]]))
      review_stats$unit_containments = review_stats$unit_containments + 1L
    }
    for (j in setdiff(live, i)) {
      source_meta = frame$available_inverse[[i]]
      target_meta = frame$available_inverse[[j]]
      matrix = frame$is_not_subset_of[[source_meta]]
      exact = vapply(colnames(matrix), function(s) {
        !all(entries[[i]][[s]] %in% entries[[j]][[s]])
      }, logical(1))
      stopifnot(identical(unname(matrix[target_meta, ]), unname(exact)))
      stopifnot(frame$not_subset_count[source_meta, target_meta] == sum(exact))
      stopifnot(sum(exact) > 0L)
      review_stats$live_pair_checks = review_stats$live_pair_checks + 1L
    }
  }
  review_stats$boundaries = review_stats$boundaries + 1L
}

review_target_start = function(frame, is_unit_target) {
  donors = if (is_unit_target) frame$remaining_nonunit_entries else frame$remaining_other_entries
  expected = review_propagate(frame$entries[donors], frame$clause, frame$universe)
  assign("review_expected", expected, envir = frame)
  review_stats$targets = review_stats$targets + 1L
}

review_iteration = function(frame, is_unit_target) {
  donors = if (is_unit_target) frame$remaining_nonunit_entries else frame$remaining_other_entries
  counts = if (is_unit_target) frame$not_subset_count else frame$not_subset_count_current
  stopifnot(length(counts) == length(donors))
  for (j in seq_along(donors)) {
    donor = frame$entries[[donors[[j]]]]
    exceptional = names(donor)[vapply(names(donor), function(s) {
      !all(donor[[s]] %in% frame$clause[[s]])
    }, logical(1))]
    stopifnot(counts[[j]] == length(exceptional), length(exceptional) > 0L)
    if (is_unit_target) {
      bits = frame$is_not_subset_of_unit[[j]]
      if (!is.null(bits)) stopifnot(setequal(names(bits)[bits], exceptional))
    } else {
      source_meta = frame$available_inverse[[donors[[j]]]]
      matrix = frame$is_not_subset_of[[source_meta]]
      stopifnot(setequal(colnames(matrix)[matrix[frame$meta_idx, ]], exceptional))
    }
    if (frame$was_used[[j]]) {
      stopifnot(length(exceptional) == 1L)
      s = exceptional[[1L]]
      possible = setdiff(frame$universe[[s]], frame$clause[[s]])
      stopifnot(length(possible) > 0L, all(possible %in% donor[[s]]))
      review_stats$used_donor_checks = review_stats$used_donor_checks + 1L
    }
    review_stats$virtual_pair_checks = review_stats$virtual_pair_checks + 1L
  }
}

review_target_end = function(frame) {
  stopifnot(identical(frame$eliminated[[frame$clause_idx]], frame$review_expected))
}

replace_once = function(source, old, new) {
  offsets = gregexpr(old, source, fixed = TRUE)[[1L]]
  stopifnot(length(offsets) == 1L, offsets[[1L]] > 0L)
  sub(old, new, source, fixed = TRUE)
}

src = paste(readLines("R/CnfFormula_simplify.R"), collapse = "\n")
src = replace_once(src,
  "  remaining_entries = which(!eliminated)[order(lengths(entries[!eliminated]), decreasing = TRUE)]",
  paste0("  review_boundary(environment())\n",
    "  remaining_entries = which(!eliminated)[order(lengths(entries[!eliminated]), decreasing = TRUE)]"))
src = replace_once(src, "    repeat {\n      # we do HLA",
  paste0("    review_target_start(environment(), FALSE)\n",
    "    repeat {\n      review_iteration(environment(), FALSE)\n      # we do HLA"))
src = replace_once(src, "    }\n  }\n\n  # We now do the same thing as above, only for units.",
  "    }\n    review_target_end(environment())\n  }\n\n  # We now do the same thing as above, only for units.")
src = replace_once(src, "    # The following loop is mostly identical to the loop above, only for units.\n    repeat {",
  paste0("    # The following loop is mostly identical to the loop above, only for units.\n",
    "    review_target_start(environment(), TRUE)\n    repeat {\n",
    "      review_iteration(environment(), TRUE)"))
src = replace_once(src, "    }\n  }\n\n  return_entries(entries[!eliminated])",
  "    }\n    review_target_end(environment())\n  }\n\n  return_entries(entries[!eliminated])")
eval(parse(text = src))
audited_simplify = simplify_cnf

encode_result = function(result, universe) {
  if (is.logical(result)) return(if (result) "TRUE" else "FALSE")
  paste(vapply(result, function(clause) {
    paste(vapply(names(universe), function(s) {
      sum(2L ^ (match(clause[[s]], universe[[s]]) - 1L))
    }, numeric(1)), collapse = ",")
  }, character(1)), collapse = ";")
}

run_request = function(request) {
  for (s in c("boundaries", "registries", "unit_containments", "live_pair_checks",
    "targets", "virtual_pair_checks", "used_donor_checks")) review_stats[[s]] = 0L
  universe = setNames(lapply(request$domains, function(size) as.character(seq_len(size) - 1L)),
    paste0("s", seq_along(request$domains)))
  entries = lapply(request$clauses, function(clause) {
    literals = Map(function(mask, domain) {
      domain[bitwAnd(mask, 2L ^ (seq_along(domain) - 1L)) != 0L]
    }, clause, universe)
    names(literals) = names(universe)
    literals[lengths(literals) > 0L]
  })
  result = plain_simplify(entries, universe)
  audited = audited_simplify(entries, universe)
  stopifnot(identical(result, audited))
  stats = as.list(review_stats)
  paste("OK", encode_result(result, universe),
    paste(paste(names(stats), unlist(stats), sep = "="), collapse = ","), sep = "\t")
}

input = file("stdin", "r")
repeat {
  line = readLines(input, n = 1L, warn = FALSE)
  if (!length(line)) break
  answer = tryCatch(run_request(eval(parse(text = line))),
    error = function(error) paste("ERROR", conditionMessage(error), sep = "\t"))
  cat(answer, "\n", sep = "")
  flush.console()
}
