list(R = "R version 3.6.3 (2020-02-29)", sha256 = "7d34ad60035509a463168752bb5f6f82d87fd7182a94a0e48461be7cdbe35fdc",
    cases = 31L, helper_entries = 2267L, nested_apply_entries = 362L,
    max_helpers = 36L, max_apply = 12L, max_apply_free_segment = 4L,
    helper_counts = c(char_intersect = 336L, char_setdiff = 418L,
    char_union = 9L, return_entries = 31L, register_unit = 124L,
    apply_domain_restriction = 579L, eliminate_symbol_from_clause = 146L,
    on_updated_subset_relations = 493L, on_update_range = 9L,
    handle_sse_2nd_order_oneend = 12L, handle_sse_2nd_order_twoend = 32L,
    try_sse_2nd_order = 72L, eliminate_clause_update_sr = 6L),
    observed_edges = c(`apply_domain_restriction -> char_intersect` = 166L,
    `apply_domain_restriction -> eliminate_clause_update_sr` = 3L,
    `apply_domain_restriction -> eliminate_symbol_from_clause` = 146L,
    `eliminate_symbol_from_clause -> register_unit` = 102L, `on_updated_subset_relations -> apply_domain_restriction` = 462L,
    `on_updated_subset_relations -> handle_sse_2nd_order_twoend` = 27L,
    `handle_sse_2nd_order_twoend -> try_sse_2nd_order` = 54L,
    `try_sse_2nd_order -> apply_domain_restriction` = 9L, `char_intersect -> char_union` = 9L,
    `apply_domain_restriction -> on_updated_subset_relations` = 12L,
    `on_updated_subset_relations -> handle_sse_2nd_order_oneend` = 6L,
    `handle_sse_2nd_order_oneend -> try_sse_2nd_order` = 18L,
    `on_updated_subset_relations -> eliminate_clause_update_sr` = 1L,
    `apply_domain_restriction -> on_update_range` = 9L, `eliminate_symbol_from_clause -> on_updated_subset_relations` = 285L,
    `register_unit -> apply_domain_restriction` = 73L, `on_update_range -> handle_sse_2nd_order_oneend` = 6L,
    `on_update_range -> handle_sse_2nd_order_twoend` = 5L))
